version: '3.5'

services:
  allwayswithyou-website:
    image: ${ALLWAYSWITHYOU_WEBSITE_IMAGE_NAME_PROD:-allwayswithyou/website}:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_ENV=production
