apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: website-deployment
  labels:
    app: allwayswithyou
    component: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: allwayswithyou
      component: website
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: allwayswithyou
        component: website
    spec:
      containers:
      - name: content
        image: $ALLWAYSWITHYOU_WEBSITE_IMAGE_NAME_STAGING:$TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regsec