apiVersion: v1
kind: Service
metadata:
  labels:
    app: allwayswithyou
    component: website
  name: website
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: allwayswithyou
    component: website